apiVersion: v1
kind: Service
metadata:
  labels:
    app: exporter-kube-scheduler
    component: kube-scheduler
  name: exporter-kube-scheduler
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10251
      protocol: TCP
      targetPort: 10251
  selector:
    k8s-app: kube-scheduler
  type: ClusterIP
