apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: exporter-kube-scheduler
    component: kube-scheduler
    prometheus: cluster
  name: exporter-kube-scheduler
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: exporter-kube-scheduler
      component: kube-scheduler
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
    - port: http-metrics
      interval: 15s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
