apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: prometheus
    prometheus: cluster
  name: prometheus
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager
        port: http
  baseImage: "quay.io/prometheus/prometheus"
  paused: false
  replicas: 1
  logLevel: info
  routePrefix: "/"
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      prometheus: cluster
  ruleSelector:
    matchLabels:
      prometheus: cluster
  ruleNamespaceSelector: {}
  version: "v2.2.1"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: prometheus
                prometheus: "cluster"
