apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: exporter-node
  name: psp-exporter-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-exporter-node
subjects:
  - kind: ServiceAccount
    name: exporter-node
