apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: exporter-kube-state
  name: exporter-kube-state
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: exporter-kube-state
subjects:
  - kind: ServiceAccount
    name: exporter-kube-state
