apiVersion: v1
kind: Service
metadata:
  name: exporter-kube-state
  labels:
    app: exporter-kube-state
    component: kube-state
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: kube-state-metrics
  selector:
    app: exporter-kube-state
